### ISSUE TITLE
Create Routing for app

### ISSUE THREAD

**Issue by medlenmage** [medlenmage/capstone-gamer-log#14]
### **Dev Story**
---
As a developer i should see a App.js file. In the App file i should see a Browser Router, Redirect, Route, and Switch imported from react-router-dom. I should see two functions one for private routing and one for public routing. In the render return i should see inside a browser router call a switch call with 6 private routes and 1 public route. In the routes i should see where they are routing to in the path properties and see the components they are going to in the component property.

### **AC**
---
**When** the dev examines the code in App.js they should see a import that has Browser Router, redirect, route, and switch coming in
**The** dev should see two functions one for private routing and one for public
**Then** they should see down in the render return a browser router call
**Then** inside the browser router they should see a switch call
**Then** inside the switch call they should see 6 private routing calls and 1 public
**Then** inside the routing calls there should be a path, component, and auth calls inside
**Finally** they should see a redirect call at the bottom of the switch call

### **To Do**
---
- [x] Import Browser Router, Redirect, Route, and Switch from react-router-dom into App.js
- [x] Create a PrivateRoute function that checks if the user is authed and redirects to Home/Games page( #17  )
- [x] Create a PublicRouter function that checks if the user is not authed and redirects to the landing page( #16 )
- [x] Inside the render return call BrowserRouter
- [x] Inside the BrowserRouter call the navbar
- [x] Inside the BrowserRouter call a Switch statement
- [x] Inside the switch statement call PrivateRoute 6 times
- [x] Inside the PrivateRoutes path to games page, logs page, new game, update game, new log, update log.
- [x] Inside the switch statement call PublicRoute
- [x] Inside the PublicRoute pathing to the landing page(#16 )
- [x] Call redirect that redirects to home page from anywhere(if authed)
- [x] Call auth in all private routes and public route

### **Sample code**
---
```
<div className="App">
        <BrowserRouter>
          <>
            <MyNavbar authed={authed} />
            <div className="container">
              <Switch>
                <PrivateRoute path="/home" component={Home} authed={authed} />
                <PrivateRoute path="/new" component={NewStuff} authed={authed} />
                <PrivateRoute path="/games" component={MyStuff} authed={authed} />
                <PrivateRoute path="/edit-game/:gameId" component={Edit} authed={authed} />
                <PrivateRoute path="/logs/:gameId" component={SingleStuff} authed={authed} />
                <PublicRoute path="/auth" component={Auth} authed={authed} />
                <Redirect from="*" to="/home"/>
              </Switch>
            </div>
          </>
        </BrowserRouter>
      </div>
```
